import { readFile, mkdir, writeFile } from 'node:fs/promises'
import { dirname, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

// Join this library's static ES modules in dependency order. Unsupported module
// syntax fails the build, so no runtime package or downloaded bundler is needed.
const root = fileURLToPath(new URL('../', import.meta.url))

async function bundle(entry, node = false) {
  const modules = new Map()
  const visiting = new Set()
  const id = file => relative(root, file).replaceAll('\\', '/')
  async function visit(file) {
    if (modules.has(file)) return
    if (visiting.has(file)) throw new Error(`Circular module dependency: ${id(file)}`)
    visiting.add(file)
    let source = await readFile(file, 'utf8')
    const exports = []
    const references = [...source.matchAll(/^(?:import\s+(?:[A-Za-z_$][\w$]*|\{[^}]*\})|export\s+\{[^}]*\})\s+from\s+['"]([^'"]+)['"];?[ \t]*$/gm)]
    const reference = specifier => {
      if (specifier === 'node:crypto' && node) return 'require("node:crypto")'
      if (!specifier.startsWith('./') && !specifier.startsWith('../')) {
        throw new Error(`External dependency is not supported in this bundle: ${specifier}`)
      }
      return `__modules[${JSON.stringify(id(resolve(dirname(file), specifier)))}]`
    }
    for (const match of references) {
      const specifier = match[1]
      reference(specifier)
      if (specifier.startsWith('.')) await visit(resolve(dirname(file), specifier))
    }
    source = source.replace(/^import\s+([\s\S]*?)\s+from\s+['"]([^'"]+)['"];?\s*$/gm, (_, binding, specifier) => {
      const value = reference(specifier)
      if (/^\{[\s\S]*\}$/.test(binding.trim())) {
        return `const ${binding.replace(/\bas\b/g, ':')} = ${value};\n`
      }
      if (!/^[A-Za-z_$][\w$]*$/.test(binding.trim())) throw new Error(`Unsupported import in ${id(file)}`)
      return `const ${binding.trim()} = ${value}.default;\n`
    })
    source = source.replace(/^export\s+\{([\s\S]*?)\}\s+from\s+['"]([^'"]+)['"];?\s*$/gm, (_, names, specifier) => {
      const value = reference(specifier)
      for (const name of names.split(',').map(item => item.trim()).filter(Boolean)) {
        if (!/^[A-Za-z_$][\w$]*$/.test(name)) throw new Error(`Unsupported re-export in ${id(file)}`)
        exports.push(`${JSON.stringify(name)}: ${value}[${JSON.stringify(name)}]`)
      }
      return ''
    })
    source = source.replace(/^export default class ([A-Za-z_$][\w$]*)/gm, (_, name) => {
      exports.push(`default: ${name}`)
      return `class ${name}`
    })
    source = source.replace(/^export (class|function|const) ([A-Za-z_$][\w$]*)/gm, (_, kind, name) => {
      exports.push(`${JSON.stringify(name)}: ${name}`)
      return `${kind} ${name}`
    })
    if (/^\s*(import|export)\s/m.test(source)) throw new Error(`Unsupported module syntax in ${id(file)}`)
    modules.set(file, `__modules[${JSON.stringify(id(file))}] = (() => {\n${source}\nreturn { ${exports.join(', ')} };\n})();`)
    visiting.delete(file)
  }
  const entryFile = resolve(root, entry)
  await visit(entryFile)
  return `(() => {\n'use strict';\nconst __modules = Object.create(null);\n${[...modules.values()].join('\n')}\nreturn __modules[${JSON.stringify(id(entryFile))}];\n})()`
}

await mkdir(resolve(root, 'dist'), { recursive: true })
await writeFile(resolve(root, 'dist/index.cjs'),
  `// Generated by npm run build.\nconst library = ${await bundle('index.js', true)};\nmodule.exports = Object.assign(library.default, library);\n`)
await writeFile(resolve(root, 'dist/google-apps-script-build.js'),
  `// Generated by npm run build. Paste into an Apps Script V8 project.\nvar BinanceStocksLibrary = ${await bundle('src/BinanceStocks.js')};\nvar BinanceStocks = BinanceStocksLibrary.default;\n`)
